# A workflow run is made up of one or more jobs that can run
# sequentially or in parallel
on: [push, pull_request]
name: Run tests

jobs:
  tests:
    name: Tests

    strategy:
      matrix:
        # TODO add windows-latest
        os: [ubuntu-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Prepare java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    # - uses: joschi/setup-jdk@v2
    #   with:
    #     java-version: '11' # The OpenJDK version to make available on the path
    #     architecture: 'x64' # defaults to 'x64'

    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@10.1
      with:
        cli: 1.11.1.1208

    - name: Install node
      uses: actions/setup-node@v3
      with:
       node-version: '16'

    - name: Install vega-cli
      run: |
        npm install -g vega vega-lite vega-cli

    - name: Install babashka
      uses: turtlequeue/setup-babashka@v1.5.0
      with:
        babashka-version: 0.7.0

    - name: Setup clj-kondo
      uses: DeLaGuardo/setup-clj-kondo@master
      with:
        version: '2024.09.27'

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0          # all commits for git-rev-count

    - name: build jar
      run: |
        set -x
        clojure -T:build jar :project :criterium :verbose true

    - name: prep deps
      run: |
        set -x
        clojure -T:build javac :project :agent :class-dir '"bases/agent/target/classes"' :verbose true
        ls -laR bases/agent/target/classes/ || echo "No target/classes directory"
        clojure -P -A:test:dev

    - name: test
      run: |
        set -x
        clojure -M:kaocha:dev:test --reporter dots

    - name: cache clj-kondo configs
      run: |
        set -x
        clj-kondo --lint $(clojure -Spath -A:dev:test) --dependencies --copy-configs --skip-lint

    - name: lint
      run: |
        set -x
        clj-kondo --lint bases projects --fail-level warning
